### ISSUE TITLE
Proper nesting of headings in CONTRIBUTING.md

### ISSUE THREAD

**Issue by joelhans** [netdata/.github#3]
There should only be a single h1 heading (`#`) in any given `.md` file, but `CONTRIBUTING.md` has multiple.

This should be addressed by moving h1s to h2s, h2s to h3s, and so on, as appropriate based on the nesting of different sections. I would have done this myself, but I felt like I didn't have a great grasp on the overall structure and would only mess up the nesting.

**Comment by odyslam** [comment]
No worries @joelhans, it is my responsibility. Thanks for mentioning that, Headings have always baffled me. 

I use multiple h1 so that I have more options to nest things.
